//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseContainer : DbContext
    {
        public DataBaseContainer()
            : base("name=DataBaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Serviices> Service { get; set; }
        public virtual DbSet<TypeService> TypeService { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<RequestService> RequestService { get; set; }
        public virtual DbSet<RequestEmployee> RequestEmployee { get; set; }
        public virtual DbSet<EmployeeService> EmployeeService { get; set; }
    }
}
