//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestEmployee
    {
        public int EmployeeID { get; set; }
        public int RequestID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Request Request { get; set; }
    }
}
